name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  tests:
    name: PHP tests
    runs-on: ubuntu-latest
    container:
      image: composer:2.3.7
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        run: composer cs-fixer