name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  tests:
    name: PHP tests
    runs-on: ubuntu-latest
    container:
      image: composer:2.3.7
      volumes:
        - ${{ github.workspace }}:/usr/src/myapp
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run php cs fixer
        run: composer cs-fixer
      - name: Run PHPStan
        run: composer phpstan
      - name: Run PHPUnit
        run: composer phpunit
